// Code generated by MockGen. DO NOT EDIT.
// Source: ./customer.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "hexagonal_project/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomerServicePort is a mock of CustomerServicePort interface.
type MockCustomerServicePort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerServicePortMockRecorder
}

// MockCustomerServicePortMockRecorder is the mock recorder for MockCustomerServicePort.
type MockCustomerServicePortMockRecorder struct {
	mock *MockCustomerServicePort
}

// NewMockCustomerServicePort creates a new mock instance.
func NewMockCustomerServicePort(ctrl *gomock.Controller) *MockCustomerServicePort {
	mock := &MockCustomerServicePort{ctrl: ctrl}
	mock.recorder = &MockCustomerServicePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerServicePort) EXPECT() *MockCustomerServicePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerServicePort) Create(ctx context.Context, data entity.Customer) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerServicePortMockRecorder) Create(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerServicePort)(nil).Create), ctx, data)
}

// Delete mocks base method.
func (m *MockCustomerServicePort) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerServicePortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerServicePort)(nil).Delete), ctx, id)
}

// GetInfo mocks base method.
func (m *MockCustomerServicePort) GetInfo(ctx context.Context, id uint64) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx, id)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockCustomerServicePortMockRecorder) GetInfo(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockCustomerServicePort)(nil).GetInfo), ctx, id)
}

// GetList mocks base method.
func (m *MockCustomerServicePort) GetList(ctx context.Context, filter map[string]interface{}, args ...interface{}) (int64, []entity.Customer, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetList", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]entity.Customer)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockCustomerServicePortMockRecorder) GetList(ctx, filter interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockCustomerServicePort)(nil).GetList), varargs...)
}

// Update mocks base method.
func (m *MockCustomerServicePort) Update(ctx context.Context, id uint64, data map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerServicePortMockRecorder) Update(ctx, id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerServicePort)(nil).Update), ctx, id, data)
}
